### ISSUE TITLE
DaggerAppComponent not create

### ISSUE THREAD

**Issue by ethaannn** [a1018875550/Kotlin-MVP-dagger2#1]
我下载你的demo 学习一下， 配置好环境  DaggerAppComponent 无法自动生成。想请教一下！

**Comment by MichaelJokAr** [comment]
把gradle console报的错截图来看下

**Comment by ethaannn** [comment]
gradle console 没有错误， 就是DaggerAppComponent 无法自动生成  要不加个微信jsfxhhq  比较方便

**Comment by MichaelJokAr** [comment]
加我QQ把，就是这个id后面的数字
